### ISSUE TITLE
what

### ISSUE THREAD

**Issue by punmechanic** [Ba3a-G/Check-Valorant#1]
lmao please don't encourage people to use their password in third party services

**Comment by bdowne01** [comment]
Seriously.  I just ran across this because my son asked for help setting up an AWS Lambda function.   Said 'sure', and asked what code he was using.

- Code source is to a .zip in a public bucket with no way to validate it (versus using a github release system)
- Login Credentials are stored in the clear as environment variables (versus using Secrets Manager)
- API Gateway configuration as describe effectively gives anyone who guesses the URL authority to execute against the riotgames API as you, with zero authorization.

Amateur hour folks.  Run away.

**Comment by Ba3a-G** [comment]
Hey,
Thanks for your input. We wanted to make the process as simple as possible, so, we had to make some tradeoffs. Coming to your suggestions:

1. Because Lambda accepts files directly from S3, plus unauthorized users can't tamper it, plus simpler to do
2. To reduce complexity, plus you can do it through Secrets Manager if you want
3. How do you guess a random string? Please enlighten me

Unfortunately, we could not find any other way of getting access token without password except for asking it on an URL. Please help us find an alternative way and we will definitely integrate it.

Also, yup we are amateur, learning and building stuff along the way.

**Comment by bdowne01** [comment]
I appreciate the candor.  But this really should be pulled down.   I work as a cloud architect and an Infosec professional.   Fortunately it appears Riot has disabled cross-site requests to their token endpoint, which it should have been set up like in the first place. 

So some tips for your future endeavors:

1.  You should never deploy your code as a zip in a bucket with no verification is bad.  Especially your users blindly run that code.  The right way to do this is to cut a Github release, on the repo where the code is and create a deployable file there.  At least that way your users know they're getting what's being shown.  Learn how that works.  Deploying code like that with no verification leaves too many opportunities for bad code to be MITM'd.

2. Yes, but it should have been that way by default.   Putting passwords in environment variables allows leaking of that data due to it being readable by any other module you are pulling in. 

3. Computers can generate thousands & thousands of strings per second.   And frankly, if you're asking that question, you've got a long way to go.

Have a good day.

**Comment by punmechanic** [comment]
1. I don't think point 1 is necessarily bad. We don't do code verification at our company either when it comes to Lambda. If you can write to the deployment bucket, then we have bigger problems, because it means, in our case, you've gained access to an engineer's AWS account that can only be accessed via a federated authentication service.
2. You should use something like Vault or AWS secrets manager, but again, this is only _really_ a problem if someone gains access to your AWS console. If they gain access to your AWS console, even on a developer account and not on the root one, they can presumably replace the Lambda function to one that prints creds anyway, so this is not such a big deal. Although, this is more of a big deal when you cannot guarantee everyone accessing the system also should be permitted to modify the Lambda.
3. The way around this would be to use some kind of API key system using a complex key that cannot be easily guessed, like a GUID, or to use federated authentication.  You'd also want some kind of rate limiting.

> Also, yup we are amateur, learning and building stuff along the way.

You cannot be an amateur and create things that take in usernames and passwords for services you do not control, on accounts that may have a net worth of thousands of dollars.

This project is in violation of Riot's terms of service and is dangerous. Frankly, even if you addressed all the nitpicks by @bdowne01, there is no way that this service could be secure based on solely on the fact that it handles usernames and passwords of Riot accounts. _At a fundamental level, as long as this service accepts usernames and passwords, it cannot ever be secure nor should anyone use it_. The entire security of this project is based on the premise of "trust me guy, I totally won't log in to your account unless you ask me to", which you absolutely could do if you wanted to.

Unless and until Riot releases a system that allows for federated auth (like OAuth), ethically, I think you should take this service down.

**Comment by Ba3a-G** [comment]
We have shut down the project. Hope they support OAuth soon. 🫡
